
# This file defines the Rust style for automatic reformatting.
# See also https://rust-lang.github.io/rustfmt

# Rust language edition to be used by the parser.
edition = "2021"

# Line endings will be converted to \n.
newline_style = "Unix"
